[package]
name = "nymph-codegen"
description = "JavaScript code generation from the Nymph HIR."
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nymph-hir = { workspace = true }
oxc = { workspace = true }
ecow = { workspace = true }

[dev-dependencies]
nymph-sema = { workspace = true }
nymph-syntax = { workspace = true }
