[package]
name = "nymph-cli"
description = "A simple language that gets out of your way."
version = "0.1.0"
edition = "2024"
homepage = "https://nymphlang.dev/"
repository = "https://github.com/theonlytails/nymph_lang"
license = "Apache-2.0"
authors = ["Shachar Zidon <theonlytails@theonlytails.com>"]
keywords = ["language", "programming-language", "parser", "lexer", "compiler"]
categories = ["compilers", "command-line-utilities", "parser-implementations"]

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5.38", features = ["derive", "cargo"] }
itertools = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reedline = "0.40.0"
nymph-compiler = { path = "../compiler" }
ariadne = "0.5.1"
rayon = { workspace = true }

[[bin]]
name = "nymph"
path = "src/main.rs"
