[package]
name = "nymph-wasm"
description = "Browser-loadable WASM module compiling Nymph source to JS + diagnostics"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nymph-compiler = { path = "../nymph-compiler", default-features = false, features = ["bundler-swc"] }
nymph-syntax.workspace = true
serde = { workspace = true }
wasm-bindgen = "0.2.126"
serde-wasm-bindgen = "0.6.5"
