[package]
name = "nymph-cli"
description = ""
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "nymph"
path = "src/main.rs"

[dependencies]
nymph-compiler = { workspace = true }
nymph-project = { workspace = true }
nymph-diagnostics = { workspace = true }
nymph-format = { path = "../nymph-format" }
ecow = { workspace = true }
clap = { workspace = true }
inquire = "0.9.4"
owo-colors = "4.3.0"
anyhow = { workspace = true }
