[package]
name = "nymph-cli"
description = ""
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nymph-sema = { workspace = true }
nymph-diagnostics = { workspace = true }
ecow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
semver = { workspace = true }
inquire = "0.9.4"
owo-colors = "4.3.0"

