[package]
name = "nymph-ast"
description = "Abstract syntax tree, tokens, and spans for the Nymph language."
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ecow = { workspace = true }
ordered-float = { workspace = true }
salsa = { workspace = true }
strum = { workspace = true }
