[package]
name = "nymph-diagnostics"
description = "Backend-agnostic diagnostics and pretty rendering for the Nymph toolchain."
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nymph-ast = { workspace = true }
ariadne = { workspace = true }
ecow = { workspace = true }

[lints.clippy]
all = "warn"
